Develop
dailymp/trivia-game-with-hooks pull request #8
Opened 2019-06-08 09:48 UTC by jfchico

Issue solved as requested.
Could not complete testing with Jest

2019-06-10 08:43 UTC, dailymp requested changes

2019-06-10 08:43 UTC, dailymp commented on src/app.tsx
> +    this.state = { begin: false, result: null }
I have been trying to get the results from browser when finish the game, but never load the results, beceause the result state is not changing and is always null... and when the last question is answered the screen doesn't change always appear like this: 
![image](https://user-images.githubusercontent.com/14187188/59183504-6fcdd500-8b6c-11e9-83fa-38ca5f84e664.png) and we can't do anything else, not even see the results or play again!

2019-06-10 08:50 UTC, jfchico commented
That is not implemented because it was not defined in the issue
requirements.

To see the results, the initial state of app can be set to results =
resultsFinish, which is a mocked results objects.

El lun., 10 jun. 2019 10:43, Daily Miranda Pardo <notifications@github.com>
escribió:

> *@dailymp* requested changes on this pull request.
> ------------------------------
>
> In src/app.tsx
> <https://github.com/dailymp/trivia-game-with-hooks/pull/8#discussion_r291926469>
> :
>
> > @@ -64,7 +64,7 @@ export class AppInner extends React.Component<Props, State> {
>     */
>    constructor(props: Props) {
>      super(props);
> -    this.state = { begin: false, result: resultFinish }
> +    this.state = { begin: false, result: null }
>
> I have been trying to get the results from browser when finish the game,
> but never load the results, beceause the result state is not changing and
> is always null... and when the last question is answered the screen doesn't
> change always appear like this:
> [image: image]
> <https://user-images.githubusercontent.com/14187188/59183504-6fcdd500-8b6c-11e9-83fa-38ca5f84e664.png>
> and we can't do anything else, not even see the results or play again!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dailymp/trivia-game-with-hooks/pull/8?email_source=notifications&email_token=AC6SIJYC6MS7U7EOJSAHXOTPZYH2DA5CNFSM4HWG4UU2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB3AKMKI#pullrequestreview-247506473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC6SIJ77UBUHNU4ITNLGOMLPZYH2DANCNFSM4HWG4UUQ>
> .
>

2019-06-10 09:10 UTC, dailymp commented
Can you implement the get Results on this issue? Thanks

2019-06-16 10:58 UTC, jfchico commented on src/app.tsx
> +    this.state = { begin: false, result: null }
All the logic to finish the game has been implemented to get the getResults method working.

A 'Finish' button is showing when the user is in the last question allowing them to finalize the game. This would render the results screen.

In addition, every component is working now with hooks (app, questionsBox and questionsItem were not being implemented with hooks)

2019-06-17 08:59 UTC, dailymp commented on src/components/questionBox.tsx
> +  componentWillReceiveProps = (nextProps: Props) => {
componentWillReceiveProps should not be used anymore, 
![image](https://user-images.githubusercontent.com/14187188/59591741-d0ba5780-90ee-11e9-9ccd-04b4b518a0ec.png)

2019-06-17 09:12 UTC, dailymp reviewed
I was testing the app in action, and I could see some problems of synchrony, 
sometimes the question box is loaded empty. Nonetheless, I like your overall work.

2019-06-17 09:12 UTC, dailymp commented on src/components/questionBox.tsx
> -    if (this.props.question !== nextProps.question) {
Ok, great work, you should not use this method anymore!

2019-06-17 09:12 UTC, dailymp commented on src/components/questionBox.tsx
> +            question.type === 'boolean' &&
We must use enums in this cases, to avoid strings like this : 'boolean'

2019-06-19 14:20 UTC, merged